services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  OutputDataConfigToolkitBundle\Controller\:
    resource: '../../Controller/*'
    tags:
        - { name: outputdataconfigtoolkitbundle.controller }
